// ═══════════════════════════════════════════════════
// Mock Data — SportShield AI
// Demo data for hackathon prototype
// ═══════════════════════════════════════════════════

export const mockDetections = [
  {
    id: 'DET-001',
    officialFile: 'UCL_Final_2025_HD.mp4',
    suspiciousFile: 'free_ucl_stream_copy.mp4',
    matchPercentage: 94.7,
    riskLevel: 'High',
    editedCopy: true,
    modifications: ['Cropped', 'Watermark removed', 'Resolution reduced'],
    timestamp: '2026-04-22T08:15:00Z',
    status: 'Active',
    source: 'YouTube Re-upload',
  },
  {
    id: 'DET-002',
    officialFile: 'PremierLeague_R32_Arsenal.mp4',
    suspiciousFile: 'arsenal_goals_compilation.mp4',
    matchPercentage: 87.2,
    riskLevel: 'High',
    editedCopy: true,
    modifications: ['Trimmed', 'Audio replaced', 'Logo overlay added'],
    timestamp: '2026-04-22T07:30:00Z',
    status: 'Active',
    source: 'Telegram Channel',
  },
  {
    id: 'DET-003',
    officialFile: 'LaLiga_ElClasico_2026.mp4',
    suspiciousFile: 'real_barca_highlights_hd.mp4',
    matchPercentage: 71.5,
    riskLevel: 'Medium',
    editedCopy: true,
    modifications: ['Speed altered', 'Color grading changed'],
    timestamp: '2026-04-21T22:45:00Z',
    status: 'Resolved',
    source: 'Piracy Website',
  },
  {
    id: 'DET-004',
    officialFile: 'NBA_Playoffs_Lakers.mp4',
    suspiciousFile: 'lakers_dunk_reel.mp4',
    matchPercentage: 62.3,
    riskLevel: 'Medium',
    editedCopy: true,
    modifications: ['Cropped vertically', 'Text overlay'],
    timestamp: '2026-04-21T19:10:00Z',
    status: 'Investigating',
    source: 'Twitter/X Post',
  },
  {
    id: 'DET-005',
    officialFile: 'F1_Monaco_GP_2026.mp4',
    suspiciousFile: 'monaco_race_live_free.mp4',
    matchPercentage: 98.1,
    riskLevel: 'High',
    editedCopy: false,
    modifications: ['Direct copy'],
    timestamp: '2026-04-21T16:00:00Z',
    status: 'Active',
    source: 'Illegal Streaming Site',
  },
  {
    id: 'DET-006',
    officialFile: 'Wimbledon_Finals_2026.mp4',
    suspiciousFile: 'tennis_final_watch.mp4',
    matchPercentage: 45.8,
    riskLevel: 'Low',
    editedCopy: true,
    modifications: ['Heavy editing', 'Commentary replaced'],
    timestamp: '2026-04-21T12:30:00Z',
    status: 'Dismissed',
    source: 'Facebook Live',
  },
  {
    id: 'DET-007',
    officialFile: 'IPL_2026_Final.mp4',
    suspiciousFile: 'ipl_final_leaked_stream.mp4',
    matchPercentage: 91.3,
    riskLevel: 'High',
    editedCopy: true,
    modifications: ['Resolution downscaled', 'Watermark cropped'],
    timestamp: '2026-04-20T20:00:00Z',
    status: 'Active',
    source: 'Piracy Website',
  },
  {
    id: 'DET-008',
    officialFile: 'SuperBowl_LXI_Halftime.mp4',
    suspiciousFile: 'superbowl_halftime_show.mp4',
    matchPercentage: 33.1,
    riskLevel: 'Low',
    editedCopy: true,
    modifications: ['Remixed audio', 'Fan camera angle'],
    timestamp: '2026-04-20T14:00:00Z',
    status: 'Dismissed',
    source: 'YouTube Upload',
  },
];

export const mockOfficialContent = [
  { id: 'OFF-001', name: 'UCL_Final_2025_HD.mp4', type: 'video', size: '2.4 GB', uploaded: '2026-04-20', fingerprint: 'a3f8c1b2', status: 'Active' },
  { id: 'OFF-002', name: 'PremierLeague_R32_Arsenal.mp4', type: 'video', size: '1.8 GB', uploaded: '2026-04-19', fingerprint: 'b7d2e9f1', status: 'Active' },
  { id: 'OFF-003', name: 'LaLiga_ElClasico_2026.mp4', type: 'video', size: '3.1 GB', uploaded: '2026-04-18', fingerprint: 'c5a4f3d8', status: 'Active' },
  { id: 'OFF-004', name: 'NBA_Playoffs_Lakers.mp4', type: 'video', size: '1.2 GB', uploaded: '2026-04-17', fingerprint: 'd9e7b2c6', status: 'Active' },
  { id: 'OFF-005', name: 'F1_Monaco_GP_2026.mp4', type: 'video', size: '4.6 GB', uploaded: '2026-04-16', fingerprint: 'e2f1a8d4', status: 'Active' },
  { id: 'OFF-006', name: 'Wimbledon_Finals_2026.mp4', type: 'video', size: '2.9 GB', uploaded: '2026-04-15', fingerprint: 'f6c3b7e9', status: 'Active' },
  { id: 'OFF-007', name: 'IPL_2026_Final.mp4', type: 'video', size: '2.1 GB', uploaded: '2026-04-14', fingerprint: 'g8d5c1a3', status: 'Active' },
  { id: 'OFF-008', name: 'SuperBowl_LXI_Halftime.mp4', type: 'video', size: '1.5 GB', uploaded: '2026-04-13', fingerprint: 'h4e9f2b7', status: 'Archived' },
];

export const mockAlerts = [
  {
    id: 'ALT-001',
    type: 'critical',
    title: 'Live Stream Piracy Detected',
    message: 'UCL Final is being illegally re-streamed on 3 platforms',
    time: '2 min ago',
    source: 'Multiple Sources',
    matchScore: 94.7,
  },
  {
    id: 'ALT-002',
    type: 'critical',
    title: 'High-Risk Copy Found',
    message: 'Premier League content copied with watermark removed',
    time: '15 min ago',
    source: 'Telegram',
    matchScore: 87.2,
  },
  {
    id: 'ALT-003',
    type: 'warning',
    title: 'Suspicious Upload Detected',
    message: 'El Clasico highlights with modified color grading',
    time: '1 hr ago',
    source: 'Piracy Website',
    matchScore: 71.5,
  },
  {
    id: 'ALT-004',
    type: 'critical',
    title: 'Direct Copy Alert',
    message: 'F1 Monaco GP — near identical copy detected',
    time: '3 hrs ago',
    source: 'Illegal Stream',
    matchScore: 98.1,
  },
  {
    id: 'ALT-005',
    type: 'warning',
    title: 'Modified Content Alert',
    message: 'NBA Lakers gameplay trimmed and reuploaded',
    time: '5 hrs ago',
    source: 'Twitter/X',
    matchScore: 62.3,
  },
  {
    id: 'ALT-006',
    type: 'critical',
    title: 'IPL Final Piracy',
    message: 'IPL Final stream detected on piracy website',
    time: '6 hrs ago',
    source: 'Piracy Website',
    matchScore: 91.3,
  },
];

export const mockChartData = [
  { name: 'Mon', detections: 12, highRisk: 4, resolved: 8 },
  { name: 'Tue', detections: 19, highRisk: 7, resolved: 11 },
  { name: 'Wed', detections: 8, highRisk: 2, resolved: 6 },
  { name: 'Thu', detections: 25, highRisk: 10, resolved: 13 },
  { name: 'Fri', detections: 31, highRisk: 14, resolved: 15 },
  { name: 'Sat', detections: 45, highRisk: 20, resolved: 22 },
  { name: 'Sun', detections: 38, highRisk: 16, resolved: 19 },
];

export const mockPieData = [
  { name: 'YouTube', value: 35, color: '#ef4444' },
  { name: 'Telegram', value: 25, color: '#f59e0b' },
  { name: 'Piracy Sites', value: 20, color: '#3b82f6' },
  { name: 'Social Media', value: 12, color: '#06b6d4' },
  { name: 'Others', value: 8, color: '#8b5cf6' },
];
